www/config/routes.rb
BeerQuest::Application.routes.draw do

  # User pages
  root                               :to => "user#index",                     :as => 'home', :via => [:get, :post] # Canvas POST
  get "world-score",                :to => "user#async_world_score",         :as => 'async_world_score'
  get "bars/favorites/:page",       :to => "user#async_favorites",           :as => 'async_favorites'
  get "bars/partners/:page",        :to => "user#async_partners",            :as => 'async_partners'
  get "bars/search/:prefix/:page",  :to => "user#async_search",              :as => 'async_search'
  get "invite",                     :to => "user#invite",                    :as => 'invite'
  match "invite-done",              :to => "user#invite_end",                :as => 'invite_end', :via => [:get, :post]

  # Bar pages
  get "bar/:id",                    :to => "bar#show",                       :as => 'bar'
  get "bar/:id/messages",           :to => "bar#async_messages",             :as => 'async_bar_messages'
  get "widget/bar/:id",             :to => "bar#widget",                     :as => 'bar_widget'

  # Tutorial
  get "tutorial/:page",             :to => "tutorial#index",                 :as => 'tutorial'

  # Facebook integration
  get "session_login",              :to => "facebook#session_login",         :as => 'login'
  get "session_logout",             :to => "facebook#session_logout",        :as => 'logout'
  
  # Monitoring
  get "health",                     :to => "monitoring#health",              :as => 'monitoring'

  # Game integration
  post "start",                     :to => "game#start",                     :as => 'game_start'
  post "postscore",                 :to => "game#postscore",                 :as => 'post_score'
  post "end",                       :to => "game#end",                       :as => 'game_end'
  post "message",                   :to => "game#message",                   :as => 'endgame_message'
  post "postwall",                  :to => "game#postwall",                  :as => 'postwall'

  # Donations
  get "support-us",                 :to => "payment#index",                  :as => 'support_us'
  post "support-us/donate/:level",  :to => "payment#donate",                 :as => 'donate'
  get "support-us/enddonate/:id",   :to => "payment#end",                    :as => 'end_donate'

  # Admin & debug
  get "admin/log-as/:id" ,          :to => "admin#log_as"
  get "admin/check-game/:id",       :to => "admin#check_game"
  get "admin/restrictions",         :to => "admin#restrictions"
  get "admin/test-accounts",        :to => "admin#test_accounts"
  post "admin/new-test-account",    :to => "admin#new_test_account"

end

www/app/views/layouts/application.haml
<!DOCTYPE html>
%html{:xmlns => "http://www.w3.org/1999/xhtml", 'xmlns:fb' => "http://www.facebook.com/2008/fbml", 'xmlns:og' => "http://opengraphprotocol.org/schema/", :lang => I18n.locale}
  %head
    %title= t('meta.title')
    %meta{:charset => "utf-8"}
    %meta{:property => "og:title", :content => t('meta.title')}
    %meta{:property => "og:type", :content => "game"}
    %meta{:property => "og:url", :content => "#{BeerQuest::FB_APP_URL}"}
    %meta{:property => "og:image", :content => "#{home_url}images/bq-75-75.png"}
    %meta{:property => "og:site_name", :content => t('meta.site_name')}
    %meta{:property => "fb:app_id", :content => BeerQuest::FB_APP_ID}
    %meta{:property => "og:description", :content => t('meta.description')}
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js'
    = javascript_include_tag 'http://cdn.jquerytools.org/1.2.5/tiny/jquery.tools.min.js'
    = javascript_include_tag 'rails'
    = javascript_include_tag 'jquery.swfobject.1-1-1.min'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    = stylesheet_link_tag 'main'
    = stylesheet_link_tag 'facebox'
    = javascript_include_tag 'facebox'
    - if @css
      = stylesheet_link_tag @css
    <!--[if lte IE 6]>
    = stylesheet_link_tag 'ie6.css'
    <![endif]-->
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-18886894-1']);
      _gaq.push(['_setDomainName', '.bq-4.com']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  %body
    #fb-root
    :javascript
      var initialized = function(){};
      window.fbAsyncInit = function() {
        FB.init({appId: "#{BeerQuest::FB_API_KEY}", status: true, cookie: true, xfbml: true});
        //FB.Canvas.setAutoResize();
        FB.Array.forEach([200, 600, 1000, 2000, 5000, 10000], function(delay) {
          setTimeout(function() { FB.Arbiter.inform("setSize", FB.Canvas._computeContentSize()) }, delay);
        });
        initialized();
      };
      (function() {
        var e = document.createElement('script');
        e.async = true;
        e.src = document.location.protocol + '//connect.facebook.net/#{I18n.locale == :fr ? 'fr_FR' : 'en_US'}/all.js';
        document.getElementById('fb-root').appendChild(e);
      }());

      function reloadWorldScore() {
        $.get("#{async_world_score_url}");
      }
    #main
      #header
        #banner
          %a{:href => home_url}
            = image_tag 'logo-BQ4.png', :alt => t('beerquest'), :class => 'logo'
          .like-button
            %fb:like{:href => BeerQuest::FB_APP_URL, :layout => 'button_count'}
          .stats-container
            .stats
              #world-score
                = render :partial => 'partials/world_score'
        #nav
          %ul
            %li{:class => (@nav == 'home' ? 'current' : '')}
              = link_to t('nav.home'), home_url
            %li{:class => (@nav == 'bar' ? 'current' : '')}
              = link_to t('nav.play'), bar_url(@me.last_bar)
            %li{:class => (@nav == 'challenge' ? 'current' : '')}
              = link_to t('nav.challenge'), invite_url
            %li
              = link_to t('nav.help'), help_url, :target => '_blank'
            %li{:class => (@nav == 'support_us' ? 'current' : 'special')}
              = link_to t('nav.support'), support_us_blog_url, :target => '_blank'
            %li.last
              = link_to t('nav.blog'), blog_url, :target => '_blank'
      #flash
        - if flash[:error]
          .error= flash[:error]
        - if flash[:notice]
          .notice= flash[:notice]
      - if admin?
        #admin
          %div= "ADMIN! uid=#{@me.id} fbid=#{@me.facebook_id} fn=#{@me.full_name}"
          %div= link_to "Test accounts", :controller => 'admin', :action => 'test_accounts'
          %div= link_to "Age restrictions", :controller => 'admin', :action => 'restrictions'
      #content
        = yield
      #footer
        = link_to t('nav.blog'), blog_url, :target => '_blank'
        |
        = link_to t('nav.support'), support_us_blog_url, :target => '_blank'
        |
        = link_to t('nav.bartners'), bartners_program_url, :target => '_blank'
        %br
        = link_to t('nav.tos'), tos_url, :target => '_blank'
        |
        = link_to t('nav.privacy'), privacy_url, :target => '_blank'

www/app/views/layouts/application.html.haml
<!DOCTYPE html>
%html{:xmlns => "http://www.w3.org/1999/xhtml", 'xmlns:fb' => "http://www.facebook.com/2008/fbml", :lang => I18n.locale}
  %head
    %title= "Beer Quest - #{@me.full_name}" # TODO enlever
    %meta{:charset => "utf-8"}
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js'
    = javascript_include_tag 'http://cdn.jquerytools.org/1.2.4/tiny/jquery.tools.min.js'
    = javascript_include_tag 'rails'
    = javascript_include_tag 'jquery.swfobject.1-1-1.min'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    = stylesheet_link_tag 'http://yui.yahooapis.com/2.8.1/build/reset/reset-min.css'
    = stylesheet_link_tag 'main'
    - if @css
      = stylesheet_link_tag @css
    <!--[if lte IE 6]>
    = stylesheet_link_tag 'ie6.css'
    <![endif]-->
  %body
    #fb-root
    :javascript
      window.fbAsyncInit = function() {
        FB.init({appId: "#{BeerQuest::FB_API_KEY}", status: true, cookie: true, xfbml: false});
        FB.Canvas.setAutoResize();
      };
      (function() {
        var e = document.createElement('script');
        e.async = true;
        e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
        document.getElementById('fb-root').appendChild(e);
      }());
    #main
      #header
        #banner
          %a{:href => home_url}
            = image_tag 'logo-BQ4.png', :alt => t('beerquest'), :class => 'logo'
          %a.like-button{:href => '#'}
            = image_tag 'bt-idrink.png', :alt => t('ilike')
          .stats-container
            .stats
              = image_tag 'bierre-logo.png', :alt => t('beers'), :class => 'beer'
              .total-beers= number_with_delimiter(World.total_beers)
              .challenge-header= t 'challenge.header', :goal => number_with_delimiter(2_500_000_000)
              .challenge-value= t 'challenge.value'
        #nav
          %ul
            %li.home
              = link_to t('nav.home'), home_url
            %li
              = link_to t('nav.play'), bar_url(@me.last_bar)
            %li
              %a{:href => '#'}= t 'nav.challenge'
            %li
              %a{:href => '#'}= t 'nav.help'
            %li.special
              %a{:href => '#'}= t 'nav.support'
            %li.last
              %a{:href => '#'}= t 'nav.blog'
      #flash
        - if flash[:error]
          .error= flash[:error]
        - if flash[:notice]
          .notice= flash[:notice]
      #content
        = yield

www/app/views/layouts/widget.haml
<!DOCTYPE html>
%html{:xmlns => "http://www.w3.org/1999/xhtml", 'xmlns:fb' => "http://www.facebook.com/2008/fbml", 'xmlns:og' => "http://opengraphprotocol.org/schema/", :lang => I18n.locale}
  %head
    %title= t('meta.title')
    %meta{:charset => "utf-8"}
    %meta{:property => "og:title", :content => t('meta.title')}
    %meta{:property => "og:type", :content => "game"}
    %meta{:property => "og:url", :content => "#{BeerQuest::FB_APP_URL}"}
    %meta{:property => "og:image", :content => "#{home_url}images/bq-75-75.png"}
    %meta{:property => "og:site_name", :content => t('meta.site_name')}
    %meta{:property => "fb:app_id", :content => BeerQuest::FB_APP_ID}
    %meta{:property => "og:description", :content => t('meta.description')}
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js'
    = javascript_include_tag 'jquery.timers'
    = javascript_include_tag 'jquery.aautoscroll.2.4'
    = csrf_meta_tag
    = stylesheet_link_tag 'widget'
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-18886894-1']);
      _gaq.push(['_setDomainName', '.bq-4.com']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  %body
    = yield