www/config/routes.rb
BeerQuest::Application.routes.draw do

  # User pages
  root                               :to => "user#index",                     :as => 'home', :via => [:get, :post] # Canvas POST
  get "world-score",                :to => "user#async_world_score",         :as => 'async_world_score'
  get "bars/favorites/:page",       :to => "user#async_favorites",           :as => 'async_favorites'
  get "bars/partners/:page",        :to => "user#async_partners",            :as => 'async_partners'
  get "bars/search/:prefix/:page",  :to => "user#async_search",              :as => 'async_search'
  get "invite",                     :to => "user#invite",                    :as => 'invite'
  match "invite-done",              :to => "user#invite_end",                :as => 'invite_end', :via => [:get, :post]

  # Bar pages
  get "bar/:id",                    :to => "bar#show",                       :as => 'bar'
  get "bar/:id/messages",           :to => "bar#async_messages",             :as => 'async_bar_messages'
  get "widget/bar/:id",             :to => "bar#widget",                     :as => 'bar_widget'

  # Tutorial
  get "tutorial/:page",             :to => "tutorial#index",                 :as => 'tutorial'

  # Facebook integration
  get "session_login",              :to => "facebook#session_login",         :as => 'login'
  get "session_logout",             :to => "facebook#session_logout",        :as => 'logout'
  
  # Monitoring
  get "health",                     :to => "monitoring#health",              :as => 'monitoring'

  # Game integration
  post "start",                     :to => "game#start",                     :as => 'game_start'
  post "postscore",                 :to => "game#postscore",                 :as => 'post_score'
  post "end",                       :to => "game#end",                       :as => 'game_end'
  post "message",                   :to => "game#message",                   :as => 'endgame_message'
  post "postwall",                  :to => "game#postwall",                  :as => 'postwall'

  # Donations
  get "support-us",                 :to => "payment#index",                  :as => 'support_us'
  post "support-us/donate/:level",  :to => "payment#donate",                 :as => 'donate'
  get "support-us/enddonate/:id",   :to => "payment#end",                    :as => 'end_donate'

  # Admin & debug
  get "admin/log-as/:id" ,          :to => "admin#log_as"
  get "admin/check-game/:id",       :to => "admin#check_game"
  get "admin/restrictions",         :to => "admin#restrictions"
  get "admin/test-accounts",        :to => "admin#test_accounts"
  post "admin/new-test-account",    :to => "admin#new_test_account"

end

www/app/controllers/payment_controller.rb
class PaymentController < FacebookController

  def index
    @nav = 'support_us'
  end

  def donate
    @nav     = 'support_us'
    level    = params[:level].to_i
    donation = @me.donations.create(:level => level)
    logger.info "Starting new PayPal payment for donation #{donation.id}..."
    response = Paypal::Api.set_express_checkout(donation, "#{BeerQuest::FB_APP_URL}#{end_donate_path(donation)}", "#{BeerQuest::FB_APP_URL}#{support_us_url}")
    response.log(logger)
    if response.success
      logger.info "SetExpressCheckout success, token is #{response.token}"
      donation.paypal_token = response.token
      if donation.save
        url = PAYPAL_USER_URL + "&token=#{CGI.escape(response.token)}&useraction=commit"
        redirect_to url
      else
        logger.error "Impossible to save transaction info into the donation object (id=#{donation.id})"
        redirect_to home_url
      end
    else
      logger.error "SetExpressCheckout error (code #{response.error_code}): #{response.error_message}"
      redirect_to home_url
    end
  end

  def end
    @nav      = 'support_us'
    @donation = @me.donations.first(:id => params[:id], :status => Donation::STATUS_PENDING)
    unless @donation
      raise "invalid donation id #{params[:id]} for user #{@me.id}"
    end
    received_token    = params[:token]
    received_payer_id = params[:PayerID]
    logger.info "Checking donation #{@donation.id} on PayPal side..."
    details = Paypal::Api.get_express_checkout_details(received_token)
    details.log(logger)
    if details.success
      if details.token != received_token || details.token != @donation.paypal_token
        logger.error "PayPal returned with a token (#{details.token}) different from the one saved into donation #{@donation.id} (#{@donation.paypal_token}) or received in the URL (#{received_token})"
        redirect_to home_url
      elsif details.payer_id != received_payer_id
        logger.error "PayPal returned with a PayerID (#{details.payer_id}) different from the one received in the URL (#{received_payer_id})"
        redirect_to home_url
      else
        @donation.paypal_name           = details.name
        @donation.paypal_email          = details.email
        @donation.paypal_payer_id       = received_payer_id
        @donation.paypal_correlation_id = details.correlation_id
        @donation.paypal_amount         = details.amount
        @donation.paypal_currency       = details.currency
        @donation.status                = Donation::STATUS_AUTHORIZED
        if @donation.save
          checkout = Paypal::Api::do_express_checkout_payment(@donation)
          if checkout.success
            @donation.status = Donation::STATUS_OK
            @donation.save
          else
            logger.error "Error during payment checkout of donation #{@donation.id}: #{checkout.inspect}"
            redirect_to home_url
          end
        else
          logger.error "Impossible to save transaction completion into the donation object (id=#{@donation.id})"
          redirect_to home_url
        end
      end
    else
      logger.error "GetExpressCheckout error (code #{response.error_code}): #{response.error_message}"
      redirect_to home_url
    end
  end

end

www/app/helpers/payment_helper.rb
module PaymentHelper
end

www/app/views/payment/_right_col.haml
%td.right-col
  .beermeter
    %h2= t 'support_us.beermeter.title'
    .content= t 'support_us.beermeter.content_html', :total => number_with_delimiter(Donation.total_volume)

  #faq
    .title= t 'support_us.faq.title'
    %ul.questions
      - (1..5).each do |i|
        %li
          .question
            = image_tag 'mini-beer-yellow.png'
            = t "support_us.faq.entry#{i}.question"
          .answer= t "support_us.faq.entry#{i}.answer_html"

www/app/views/payment/end.haml
- @css = 'support_us'
%table.cols
  %tr.small
    %td.small
    %td
    %td.small
  %tr
    %td.small
    %td.unique-col

      %table.main-content
        %tr
          %td.left-col
            %h1= t 'support_us.title'
            %h2= t 'support_us.subtitle_thanks'

            .thanks-box= t "support_us.offers.offer#{@donation.level}.thanks_html"

          = render :partial => 'right_col'

    %td.small.shadow
  %tr.small
    %td.small
    %td.shadow
    %td.small.shadow

www/app/views/payment/index.haml
- @css = 'support_us'
%table.cols
  %tr.small
    %td.small
    %td
    %td.small
  %tr
    %td.small
    %td.unique-col

      %table.main-content
        %tr
          %td.left-col
            %h1= t 'support_us.title'
            %h2= t 'support_us.subtitle'

            .intro= t 'support_us.intro'

            - (1..7).each do |i|
              .offer{:id => "offer#{i}"}
                .title
                  - if i == 7
                    = link_to(portable_brewery_url, :class => 'offer-button', :target => '_blank') do
                      .button-text= t('support_us.offers.button')
                  - else
                    = link_to donate_url(i), :method => :post, :class => 'offer-button' do
                      .button-text= t('support_us.offers.button')
                  &gt;
                  = t "support_us.offers.offer#{i}.title"
                  .tag= t "support_us.offers.offer#{i}.tag"
                .description
                  = t "support_us.offers.offer#{i}.description_html"

            .warning-box
              - (1..2).each do |i|
                .warning
                  %span.title= t "support_us.warnings.warning#{i}.title"
                  %span.description= t "support_us.warnings.warning#{i}.description_html"

          = render :partial => 'right_col'

    %td.small.shadow
  %tr.small
    %td.small
    %td.shadow
    %td.small.shadow