www/config/routes.rb
BeerQuest::Application.routes.draw do

  # User pages
  root                               :to => "user#index",                     :as => 'home', :via => [:get, :post] # Canvas POST
  get "world-score",                :to => "user#async_world_score",         :as => 'async_world_score'
  get "bars/favorites/:page",       :to => "user#async_favorites",           :as => 'async_favorites'
  get "bars/partners/:page",        :to => "user#async_partners",            :as => 'async_partners'
  get "bars/search/:prefix/:page",  :to => "user#async_search",              :as => 'async_search'
  get "invite",                     :to => "user#invite",                    :as => 'invite'
  match "invite-done",              :to => "user#invite_end",                :as => 'invite_end', :via => [:get, :post]

  # Bar pages
  get "bar/:id",                    :to => "bar#show",                       :as => 'bar'
  get "bar/:id/messages",           :to => "bar#async_messages",             :as => 'async_bar_messages'
  get "widget/bar/:id",             :to => "bar#widget",                     :as => 'bar_widget'

  # Tutorial
  get "tutorial/:page",             :to => "tutorial#index",                 :as => 'tutorial'

  # Facebook integration
  get "session_login",              :to => "facebook#session_login",         :as => 'login'
  get "session_logout",             :to => "facebook#session_logout",        :as => 'logout'
  
  # Monitoring
  get "health",                     :to => "monitoring#health",              :as => 'monitoring'

  # Game integration
  post "start",                     :to => "game#start",                     :as => 'game_start'
  post "postscore",                 :to => "game#postscore",                 :as => 'post_score'
  post "end",                       :to => "game#end",                       :as => 'game_end'
  post "message",                   :to => "game#message",                   :as => 'endgame_message'
  post "postwall",                  :to => "game#postwall",                  :as => 'postwall'

  # Donations
  get "support-us",                 :to => "payment#index",                  :as => 'support_us'
  post "support-us/donate/:level",  :to => "payment#donate",                 :as => 'donate'
  get "support-us/enddonate/:id",   :to => "payment#end",                    :as => 'end_donate'

  # Admin & debug
  get "admin/log-as/:id" ,          :to => "admin#log_as"
  get "admin/check-game/:id",       :to => "admin#check_game"
  get "admin/restrictions",         :to => "admin#restrictions"
  get "admin/test-accounts",        :to => "admin#test_accounts"
  post "admin/new-test-account",    :to => "admin#new_test_account"

end

www/app/controllers/user_controller.rb
class UserController < FacebookController

  protect_from_forgery :except => [:index, :invite_end] # index: canvas POST

  BARS_PER_PAGE   = 3
  INVITE_MESSAGES = 3

  def index
    unless @me.first_login
      # User's first login: send him to the default bar
      logger.debug "This is account #{@me.id} (#{@me.full_name}) first time here!"
      @me.first_login = DateTime.now
      @me.save
      redirect_to bar_url(@me.last_bar)
      return true
    end

    @nav = 'home'
#    set_favorites(1)
#    set_partners(1)
#    set_search('(none)', 1)
  end

  def async_world_score
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def async_favorites
    set_favorites(params[:page].to_i)
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def async_partners
    set_partners(params[:page].to_i)
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def async_search
    set_search(params[:prefix], params[:page].to_i)
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def invite
    @nav     = 'challenge'
    @exclude = @me.already_invited_friends_fbids
    @invite  = 1 + rand(INVITE_MESSAGES)
  end

  def invite_end
    if params[:ids]
      logger.info "Sent the following #{params[:ids].length} invite requests with message #{session[:invite]}: #{params[:ids].inspect}"
      cred = MiniFB.authenticate_as_app(BeerQuest::FB_APP_ID, BeerQuest::FB_SECRET)
      params[:ids].each do |id|
        request = MiniFB.get(cred['access_token'], id)
        @me.invites.create({
                                   :request_id         => id,
                                   :lang               => I18n.locale,
                                   :data               => request.data,
                                   :message            => request.message,
                                   :friend_facebook_id => request.to.id,
                                   :friend_name        => request.to.name
                           })
      end
    else
      logger.warn "Invitation ended without sending any requests"
    end
    redirect_to home_url
  end

  protected

  def set_favorites(page)
    results             = @me.favorite_bars
    @favorites_page     = page
    @favorites_max_page = [1, (results.count.to_f / BARS_PER_PAGE).ceil].max
    @favorites_total    = results.count
    @favorites          = results.all(:limit => BARS_PER_PAGE, :offset => (@favorites_page - 1) * BARS_PER_PAGE)
  end

  def set_partners(page)
    results            = Bar.all
    @partners_page     = page
    @partners_max_page = [1, (results.count.to_f / BARS_PER_PAGE).ceil].max
    @partners_total    = results.count
    @partners          = results.all(:limit => BARS_PER_PAGE, :offset => (@partners_page - 1) * BARS_PER_PAGE)
  end

  def set_search(prefix, page)
    @search_prefix = prefix
    if @search_prefix == '123'
      results = Bar.all(:name.like => "1%") +
              Bar.all(:name.like => "2%") +
              Bar.all(:name.like => "3%") +
              Bar.all(:name.like => "4%") +
              Bar.all(:name.like => "5%") +
              Bar.all(:name.like => "6%") +
              Bar.all(:name.like => "7%") +
              Bar.all(:name.like => "8%") +
              Bar.all(:name.like => "9%") +
              Bar.all(:name.like => "0%")
    else
      results = Bar.all(:name.like => "#{@search_prefix}%")
    end

    @search_max_page = [1, (results.count.to_f / BARS_PER_PAGE).ceil].max
    @search_page     = page
    if !@search_page || @search_page < 1 || @search_page > @search_max_page
      @search_page = 1
    end

    @search_total = results.count
    @search       = results.all(:limit => BARS_PER_PAGE, :offset => (@search_page - 1) * BARS_PER_PAGE)
  end

end

www/app/helpers/user_helper.rb
module UserHelper

  def favorite_pages(current_page, max_page)
    result = ""
    if max_page > 1
      result += t('home.score.tabs.pages') + " "
      (1..max_page).each do |page|
        if page == current_page
          result += "<span class=\"page-link current\">#{page}</span> "
        else
          result += link_to(page.to_s, async_favorites_url(page), :remote => true, :class => 'page-link') + " "
        end
      end
      # TODO "..."
    end
    result.html_safe
  end

  def partner_pages(current_page, max_page)
    result = ""
    if max_page > 1
      result += t('home.score.tabs.pages') + " "
      (1..max_page).each do |page|
        if page == current_page
          result += "<span class=\"page-link current\">#{page}</span> "
        else
          result += link_to(page.to_s, async_partners_url(page), :remote => true, :class => 'page-link') + " "
        end
      end
      # TODO "..."
    end
    result.html_safe
  end

  def search_prefixes(current_prefix)
    result = ""
    result += link_to('123', async_search_url('123', 1), :remote => true, :class => 'page-link') + " "
    "A".ord.upto("Z".ord).each do |letter|
      result += "<br/>" if letter == "M".ord
      if letter.chr == current_prefix
        result += "<span class=\"page-link current\">#{letter.chr}</span> "
      else
        result += link_to(letter.chr, async_search_url(letter.chr, 1), :remote => true, :class => 'page-link') + " "
      end
    end
    result.html_safe
  end

  def search_pages(prefix, current_page, max_page)
    result = ""
    if max_page > 1
      result += t('home.score.tabs.pages') + " "
      (1..max_page).each do |page|
        if page == current_page
          result += "<span class=\"page-link current\">#{page}</span> "
        else
          result += link_to(page.to_s, async_search_url(prefix, page), :remote => true, :class => 'page-link') + " "
        end
      end
      # TODO "..."
    end
    result.html_safe
  end

end

www/app/views/user/_bar.haml
.bar
  .title= bar.name
  .banner
    = image_tag bar.banner_big, :alt => bar.name, :class => 'bar-banner'
  %table
    %tr
      %td.members
        = t('home.bar.member_count', :count => number_with_delimiter(bar.total_members))
      %td.high-score
        = t('home.bar.high_score')
        = bar.weekly_high_score
        = image_tag 'mini-biere.png', :alt => t('beers')
  .button
    %a{:href => bar_url(bar)}
      = image_tag "play-in-this-bar_#{I18n.locale}.png", :alt => t('home.bar.enter_button')

www/app/views/user/_bar.html.haml
.bar
  %table.bar-header
    %tr
      %td.name
        = bar.name
      %td.members
        = t 'home.score.bar.member_count', :count => number_with_delimiter(bar.total_members)
  %table.bar-content
    %tr
      %td.banner
        = image_tag bar.banner, :alt => bar.name, :class => 'bar-banner'
      %td.scores
        .score
          = t 'home.score.bar.score_7d'
          %br
          = image_tag 'mini-biere.png', :alt => t('beers')
          = bar.always_high_score_for(@me)
        .score
          = t 'home.score.bar.best_score'
          %br
          = image_tag 'mini-biere.png', :alt => t('beers')
          = bar.weekly_high_score_for(@me)
  .button
    = link_to t('home.score.bar.enter_button'), bar_url(bar)

www/app/views/user/_barscore.html.haml
%tr.barscore{:class => (barscore[:account_id] == @me.id) ? 'me' : ''}
  %td.portrait
    = image_tag barscore[:profile_picture], :alt => barscore[:full_name], :class => 'portrait'
  %td.description
    .rank= "##{barscore[:rank]}"
    .name= barscore[:full_name]
    .score
      Score :
      = image_tag 'mini-biere.png', :alt => t('beers')
      %span.value= barscore[:score]

www/app/views/user/_challenge.html.haml
%tr.challenge
  %td.portrait
    = image_tag 'avatar2.png', :class => 'portrait'
  %td.description
    .name Eric Phelippeau
    .status A gagné son round le 21.08 à 17:30
  %td.score
    = image_tag 'mini-biere.png', :alt => t('beers')
    234
  %td.action
    .button
      %a{:href => '#'} Battle

www/app/views/user/_favorite_bars.haml
%table.header
  %tr
    %td.bar-count= t 'home.score.tabs.favorites.bar_count', :count => @favorites_total
    %td.pane-pages
      = favorite_pages(@favorites_page, @favorites_max_page)
= render :partial => 'bar', :collection => @favorites

www/app/views/user/_partner_bars.haml
%table.header
  %tr
    %td.bar-count= t 'home.score.tabs.bartners.bar_count', :count => @partners_total
    %td.pane-pages
      = partner_pages(@partners_page, @partners_max_page)
= render :partial => 'bar', :collection => @partners

www/app/views/user/_scores.haml
%ul.tabs
  %li.last
    %a{:href => 'javascript:void(0)'}= t('home.scores.friends.title')
.panes
  .pane#friends-scores
    %table.score-grid
      = render :partial => 'partials/individual_score', :collection => @me.weekly_friends_scores[0...3]
      %tr
        %td.invite{:colspan => 2}
          %a{:href => invite_url}
            = image_tag "invite_#{I18n.locale}.png", :width => 162, :height => 58, :alt => t('bar.scores.invite')
      = render :partial => 'partials/individual_score', :collection => @me.weekly_friends_scores[3..-1]

www/app/views/user/_search_bars.haml
.search
  .description= t 'home.score.tabs.search.alphabetic_order'
  .values
    = search_prefixes(@search_prefix)
- if @search_prefix != '(none)'
  %table.header
    %tr
      %td.bar-count= t 'home.score.tabs.search.results', :count => @search_total, :search => @search_prefix
      %td.pane-pages
        = search_pages(@search_prefix, @search_page, @search_max_page)
  = render :partial => 'bar', :collection => @search

www/app/views/user/async_favorites.js.erb
$('#favorites').html("<%= escape_javascript(render :partial => 'favorite_bars') %>");

www/app/views/user/async_partners.js.erb
$('#bartners').html("<%= escape_javascript(render :partial => 'partner_bars') %>");

www/app/views/user/async_search.js.erb
$('#search').html("<%= escape_javascript(render :partial => 'search_bars') %>");

www/app/views/user/index.haml
- @css = 'home'
%table.cols
  %tr.small
    %td.small
    %td
    %td.small
  %tr
    %td.small
    %td.left-col
      .col-content
        %table.home
          %tr.bars
            %td.bars
              .play
                %a{:href => bar_url(@me.last_bar)}
                  = image_tag "play-now_#{I18n.locale}.png", :width => 164, :height => 74, :alt => t('home.play_now')
              .alternative= t('home.alternative')
              %table.bar-grid
                %tr
                  %td
                    = render :partial => 'bar', :object => Bar.get(1)
                  %td
                    = render :partial => 'bar', :object => Bar.get(2)
              .notice= t('home.notice_html', :link => link_to(t('home.notice_link'), bartners_program_url, :target => '_blank'))
            %td.scores
              = render :partial => 'scores'
    %td.small.shadow
  %tr.small
    %td.small
    %td.shadow
    %td.small.shadow

www/app/views/user/index.html.haml
- @css = 'home'
%table.cols
  %tr.small
    %td.small
    %td
    %td.small
    %td
    %td.small
    %td
    %td.small
  %tr
    %td.small
    %td.left-col
      = image_tag 'titre-mode-score.png', :alt => t('home.score.mode'), :class => 'col-title'
      .col-content
        %table.player
          %tr
            %td.portrait{:rowspan => 2}
              = image_tag @me.profile_picture, :alt => @me.full_name, :class => 'portrait'
            %td.score-desc= t 'home.score.best_7d'
            %td.score-value
              = image_tag 'mini-biere.png', :alt => t('beers')
              = number_with_delimiter(@me.best_score_weekly)
          %tr
            %td.score-desc= t 'home.score.total_beers'
            %td.score-value.total
              = image_tag 'mini-biere.png', :alt => t('beers')
              = number_with_delimiter(@me.total_beers)
        %table.action
          %tr
            %td.description= t 'home.score.play_description_html'
            %td.action
              .button
                %a{:href => bar_url(@me.last_bar)}= t 'home.score.button_html'
        %ul.tabs
          %li
            %a{:href => 'javascript:void(0)'}= t 'home.score.tabs.favorites.title'
          %li
            %a{:href => 'javascript:void(0)'}= t 'home.score.tabs.bartners.title'
          %li.last
            %a{:href => 'javascript:void(0)'}= t 'home.score.tabs.search.title'
        .panes
          .pane#favorites
            = render :partial => 'favorite_bars'
          .pane#bartners
            = render :partial => 'partner_bars'
          .pane#search
            = render :partial => 'search_bars'
    %td.small.shadow

    %td.separator

    %td.small
    %td.right-col
      = image_tag 'titre-mode-battle.png', :alt => t('home.battle.mode'), :class => 'col-title'
      .col-content
        %table.player
          %tr
            %td.portrait{:rowspan => 2}
              = image_tag @me.profile_picture, :alt => @me.full_name, :class => 'portrait'
            %td.score-desc= t 'home.battle.respect_points', :count => number_with_delimiter(3_450)
          %tr
            %td.score-desc= t 'home.battle.shame_points', :count => number_with_delimiter(12)
        %table.action
          %tr
            %td.description= t 'home.battle.play_description_html'
            %td.action
              .button
                %a{:href => '#'}= t 'home.battle.button_html'
        %ul.tabs
          %li
            %a{:href => 'javascript:void(0)'}= t 'home.battle.tabs.current.title'
          %li
            %a{:href => 'javascript:void(0)'}= t 'home.battle.tabs.received.title', :count => 12
          %li.last
            %a{:href => 'javascript:void(0)'}= t 'home.battle.tabs.sent.title', :count => 3
        .panes
          .pane#current
            %table.challenge-grid
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
          .pane#received
            %table.challenge-grid
              = render :partial => 'challenge'
              = render :partial => 'challenge'
          .pane#sent
            %table.challenge-grid
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
              = render :partial => 'challenge'
            .battle-warning= t 'home.battle.warning'
    %td.small.shadow
  %tr.small
    %td.small
    %td.shadow
    %td.small.shadow
    %td
    %td.small
    %td.shadow
    %td.small.shadow

www/app/views/user/invite.haml
.empty
- invite_msg = t("invite.message#{@invite}")
:javascript
  var initialized = function() {
    FB.ui({
      method: 'apprequests',
      title: "#{t('invite.selector')[0...50]}",
      message: "#{invite_msg[0...255]}",
      data: "uid=#{@me.id},msg=#{@invite}"
      //filters: [{name: "", user_ids: []}]
    }, function(response) {
      if (response && response.request_ids) {
        $.post("#{invite_end_url}", {
          authenticity_token: "#{form_authenticity_token}",
          ids: response.request_ids
        }, function() {
          window.location = "#{home_url}";
        });
      } else {
        window.location = "#{home_url}";
      }
    });
  };