www/config/routes.rb
BeerQuest::Application.routes.draw do

  # User pages
  root                               :to => "user#index",                     :as => 'home', :via => [:get, :post] # Canvas POST
  get "world-score",                :to => "user#async_world_score",         :as => 'async_world_score'
  get "bars/favorites/:page",       :to => "user#async_favorites",           :as => 'async_favorites'
  get "bars/partners/:page",        :to => "user#async_partners",            :as => 'async_partners'
  get "bars/search/:prefix/:page",  :to => "user#async_search",              :as => 'async_search'
  get "invite",                     :to => "user#invite",                    :as => 'invite'
  match "invite-done",              :to => "user#invite_end",                :as => 'invite_end', :via => [:get, :post]

  # Bar pages
  get "bar/:id",                    :to => "bar#show",                       :as => 'bar'
  get "bar/:id/messages",           :to => "bar#async_messages",             :as => 'async_bar_messages'
  get "widget/bar/:id",             :to => "bar#widget",                     :as => 'bar_widget'

  # Tutorial
  get "tutorial/:page",             :to => "tutorial#index",                 :as => 'tutorial'

  # Facebook integration
  get "session_login",              :to => "facebook#session_login",         :as => 'login'
  get "session_logout",             :to => "facebook#session_logout",        :as => 'logout'
  
  # Monitoring
  get "health",                     :to => "monitoring#health",              :as => 'monitoring'

  # Game integration
  post "start",                     :to => "game#start",                     :as => 'game_start'
  post "postscore",                 :to => "game#postscore",                 :as => 'post_score'
  post "end",                       :to => "game#end",                       :as => 'game_end'
  post "message",                   :to => "game#message",                   :as => 'endgame_message'
  post "postwall",                  :to => "game#postwall",                  :as => 'postwall'

  # Donations
  get "support-us",                 :to => "payment#index",                  :as => 'support_us'
  post "support-us/donate/:level",  :to => "payment#donate",                 :as => 'donate'
  get "support-us/enddonate/:id",   :to => "payment#end",                    :as => 'end_donate'

  # Admin & debug
  get "admin/log-as/:id" ,          :to => "admin#log_as"
  get "admin/check-game/:id",       :to => "admin#check_game"
  get "admin/restrictions",         :to => "admin#restrictions"
  get "admin/test-accounts",        :to => "admin#test_accounts"
  post "admin/new-test-account",    :to => "admin#new_test_account"

end

www/app/models/bar.rb
class Bar
  include DataMapper::Resource

  property :id, Serial
  property :name, String, :length => 100, :required => true
  property :turns, Integer, :min => 0, :default => Game::Constants::DEFAULT_INITIAL_TURNS, :required => true
  property :url, String, :length => 1024, :required => true
  property :rss_fr, String, :length => 1024
  property :rss_en, String, :length => 1024
  property :banner_big, String, :length => 1024, :required => true
  property :banner_small, String, :length => 1024, :required => true
  property :contact, String, :length => 255
  property :created_at, DateTime
  property :updated_at, DateTime

  has n, :barships, :constraint => :destroy
  has n, :accounts, :through => :barships
  has n, :replays, :constraint => :set_nil

  def self.default_bar
    self.get!(1)
  end

  def rss
    attribute_get("rss_#{I18n.locale}") || rss_en
  end

  def total_members
    barships.count
  end

  def active_members
    barships.count(:updated_at.gte => DateTime.now - 2.weeks)
  end

  def new_active_members
    barships.count(:created_at.gte => DateTime.now - 2.weeks)
  end

  def total_beers
    complete_replays.sum(:score) || 0
  end

  def weekly_beers
    weekly_complete_replays.sum(:score) || 0
  end

  def rank
    all_bars = Bar.all.sort_by { |b| -b.total_beers }
    all_bars.each_with_index do |b, i|
      return (i + 1) if b == self
    end
    0
  end

  def always_high_score
    complete_replays.max(:score) || 0
  end

  def always_high_score_for(account)
    complete_replays.all(:account_id => account.id).max(:score) || 0
  end

  def weekly_high_score
    weekly_complete_replays.max(:score) || 0
  end

  def weekly_high_score_for(account)
    weekly_complete_replays.all(:account_id => account.id).max(:score) || 0
  end

  def weekly_top_scores
    return @weekly_top_scores if @weekly_top_scores
    @weekly_top_scores = Replay.extract_bar_scores_of(self)[0...30]
  end

  def messages
    complete_replays.all(:order => :created_at.desc, :limit => 8)
  end

  private

  def complete_replays
    replays.all(:game_over => true)
  end

  def weekly_complete_replays
    complete_replays.all(:created_at.gte => DateTime.now - 2.weeks)
  end

end

www/app/controllers/bar_controller.rb
require 'rss/2.0'

class BarController < FacebookController

  def show
    @nav  = 'bar'
    @bar  = Bar.get!(params[:id])
    @mode = "solo"
    logger.debug "Creating solo replay for #{@me.full_name} (id=#{@me.id} fbid=#{@me.facebook_id}) in bar #{@bar.id}"
    @replay = @me.replays.create(:bar => @bar, :token => ActiveSupport::SecureRandom.hex(16), :ip => request.remote_ip, :mode => 'solo')
    unless @replay.saved?
      logger.error "Impossible to create replay because of the following errors:"
      @replay.errors.each do |e|
        logger.error "ERROR: #{e}"
      end
    end

    @barship = @me.barships.first(:bar => @bar) || @me.barships.create(:bar => @bar)

    # TODO limiter à un certain nombre d'entrées (7 affichables actuellement)
    if @bar.rss
      @rss = []
      begin
        open(@bar.rss) do |http|
          response = http.read
          result   = RSS::Parser.parse(response, false)
          result.items[0..10].each do |item|
            @rss << {:title => item.title, :content => item.description, :url => item.link, :date => item.pubDate}
          end
        end
      rescue OpenURI::HTTPError
        logger.error "Unable to open RSS stream #{@bar.rss} for bar #{@bar.id}"
        @rss = nil
      end
    end
  end

  def async_messages
    logger.debug "Get bar #{params[:id]}..."
    @bar = Bar.get!(params[:id])
    logger.debug "Messages for bar #{@bar.id}"
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def widget
    @bar  = Bar.get!(params[:id])
    @bgcolor = "fee734"
    @bgcolor = params[:bgcolor] if params[:bgcolor] =~ /[0-9a-z]{6}/i
    @width = 240
    @width = params[:width].to_i if params[:width].to_i >= 100 && params[:width].to_i <= 200 # TODO régler bornes
    render :layout => 'widget'
  end

end

www/app/views/bar/_header.haml
%td.bar-name{:colspan => 2}
  .relative-container
    %h1= @bar.name
    %a{:href => @bar.url, :target => '_blank'}= @bar.url
    .member-count
      = t 'bar.member_count', :count => number_with_delimiter(@bar.total_members)
      = "-"
      = t 'bar.beer_count', :count => number_with_delimiter(@bar.total_beers)
    .help
      %a.start-tutorial{:href => 'javascript:void(0)'}
        = image_tag "how-to-play_#{I18n.locale}.png", :width => 95, :height => 58, :alt => t('bar.how_to_play')
%td.bar-logo
  = image_tag @bar.banner_small, :alt => @bar.name, :class => 'bar-banner'

www/app/views/bar/_messages.haml
%h3.centered= t('bar.messages.title')
%ul.messages
  - @bar.messages.each do |msg|
    %li
      = image_tag msg.account.profile_picture, :alt => msg.account.display_name, :class => 'mini-portrait'
      = image_tag 'mini-biere.png', :alt => t('beers')
      %span.score= msg.score
      -#= "-"
      %br
      %span.name= msg.account.display_name
      -#%br
      -#%span.date= l(msg.updated_at, :format => :short)
      -#&laquo;
      -#= msg.message
      -#&raquo;

www/app/views/bar/_rss.haml
%h3= t('bar.news.title')
%ul.rss
  - @rss.each do |rss|
    %li
      %a{:href => rss[:url], :target => '_blank'}= rss[:title]

www/app/views/bar/_scores.haml
.title= t('bar.scores.title')
%ul.tabs
  %li
    %a{:href => 'javascript:void(0)'}= t('bar.scores.bar')
  %li.last
    %a{:href => 'javascript:void(0)'}= t('bar.scores.friends')
.panes
  .pane#bar-scores
    %table.score-grid
      = render :partial => 'partials/individual_score', :collection => @bar.weekly_top_scores[0...3]
      %tr
        %td.invite{:colspan => 2}
          %a{:href => invite_url}
            = image_tag "invite_#{I18n.locale}.png", :width => 162, :height => 58, :alt => t('bar.scores.invite')
      = render :partial => 'partials/individual_score', :collection => @bar.weekly_top_scores[3..-1]
  .pane#friends-scores
    %table.score-grid
      = render :partial => 'partials/individual_score', :collection => @me.weekly_friends_scores[0...3]
      %tr
        %td.invite{:colspan => 2}
          %a{:href => invite_url}
            = image_tag "invite_#{I18n.locale}.png", :width => 162, :height => 58, :alt => t('bar.scores.invite')
      = render :partial => 'partials/individual_score', :collection => @me.weekly_friends_scores[3..-1]

www/app/views/bar/_stats.haml
%table.stats
  %tr
    %td.left
      %h3= t('bar.stats.bar_stats')
      .stat
        .section
          = t 'bar.stats.bar_rank'
        .value
          = "##{@bar.rank}"
      .stat
        .section
          = t 'bar.stats.bar_weekly_activity'
        .value
          = t 'bar.stats.bar_active_members', :count => @bar.active_members
          %br
          = t 'bar.stats.bar_new_active_members', :count => @bar.new_active_members
      .stat
        .section
          = t 'bar.stats.weekly_beers'
        .value
          = image_tag 'mini-biere.png', :alt => t('beers')
          = number_with_delimiter(@bar.weekly_beers)
      .stat
        .section
          = t 'bar.stats.total_beers'
        .value
          = image_tag 'mini-biere.png', :alt => t('beers')
          = number_with_delimiter(@bar.total_beers)
    %td.right
      %h3= t('bar.stats.my_stats')
      .portrait
        = image_tag @me.profile_picture, :alt => @me.full_name, :class => 'portrait'
      .stat
        .section
          = t 'bar.stats.weekly_beers'
        .value
          = image_tag 'mini-biere.png', :alt => t('beers')
          = number_with_delimiter(@barship.weekly_beers)
      .stat
        .section
          = t 'bar.stats.total_beers'
        .value
          = image_tag 'mini-biere.png', :alt => t('beers')
          = number_with_delimiter(@barship.total_beers)
      .clear
      .stat
        .section
          = t 'bar.stats.member_since'
        .value
          = l(@barship.created_at, :format => :short)
      -#.stat
      -#  .section
      -#    = t 'bar.stats.best_rank_title'
      -#  .value
      -#    = t 'bar.stats.best_rank_value', :rank => @barship.best_rank, :date => l(@barship.best_rank_date, :format => :short)
      .stat
        .section
          = t 'bar.stats.play_count'
        .value
          = number_with_delimiter(@barship.play_count)

www/app/views/bar/async_messages.js.erb
$('#messages').html("<%= escape_javascript(render :partial => 'messages') %>");

www/app/views/bar/index.haml
- @css = 'bar'
%table.cols
  %tr.small
    %td.small
    %td
    %td.small
  %tr
    %td.small
    %td.unique-col
      %table.bar-area
        %tr
          %td.bar-name{:colspan => 2}
            %h1= @bar.name
            %a{:href => @bar.url, :target => '_blank'}= @bar.url
            .member-count
              = t 'bar.member_count', :count => number_with_delimiter(@bar.total_members)
              = "-"
              = t 'bar.beer_count', :count => number_with_delimiter(@bar.total_beers)
          %td.bar-logo
            = image_tag @bar.banner_small, :alt => @bar.name, :class => 'bar-banner'
        %tr
          %td.play-field{:colspan => 2}
            #game
          %td.sidebar
            %ul.tabs
              - if @rss
                %li
                  %a{:href => 'javascript:void(0)'}= t 'bar.right.news.title'
              %li.last
                %a{:href => 'javascript:void(0)'}= t 'bar.right.messages.title'
            .panes
              - if @rss
                .pane#rss
                  %ul.rss
                    - @rss.each do |rss|
                      %li
                        %a{:href => rss[:url], :target => '_blank'}= rss[:title]
              .pane#messages
                = render :partial => 'messages'
        %tr.bottom
          %td.bar-scores
            .panes
              .pane#barscore-7j
                %table
                  %tr
                    %td.header= t 'bar.scores.bar'
                    %td.subnav#subtabs1
                      %a{:href => 'javascript:void(0)'}= t 'bar.scores.all'
                      = "-"
                      %a{:href => 'javascript:void(0)'}= t 'bar.scores.me'
                .subpanes#subpanes1
                  .subpane
                    %table.barscore-grid
                      = render :partial => 'barscore', :collection => @bar.weekly_scores
                  .subpane
                    %table.barscore-grid
                      = render :partial => 'barscore', :collection => @bar.weekly_scores_for(@me)
              .pane#barscore-always
                %table
                  %tr
                    %td.header= t 'bar.scores.bar'
                    %td.subnav#subtabs2
                      %a{:href => 'javascript:void(0)'}= t 'bar.scores.all'
                      = "-"
                      %a{:href => 'javascript:void(0)'}= t 'bar.scores.me'
                .subpanes#subpanes2
                  .subpane
                    %table.barscore-grid
                      = render :partial => 'barscore', :collection => @bar.total_scores
                  .subpane
                    %table.barscore-grid
                      = render :partial => 'barscore', :collection => @bar.total_scores_for(@me)
            %ul.tabs
              %li
                %a{:href => 'javascript:void(0)'}= t 'bar.scores.weekly'
              %li.last
                %a{:href => 'javascript:void(0)'}= t 'bar.scores.always'
          %td.friends-scores
            .panes
              .pane#friendsscore-7j
                %table
                  %tr
                    %td.header= t 'bar.scores.friends'
                    %td.subnav#subtabs3
                      %a{:href => 'javascript:void(0)'}= t 'bar.scores.all'
                      = "-"
                      %a{:href => 'javascript:void(0)'}= t 'bar.scores.me'
                .subpanes#subpanes3
                  .subpane
                    %table.barscore-grid
                      = render :partial => 'barscore', :collection => @bar.weekly_scores
                  .subpane
                    %table.barscore-grid
                      = render :partial => 'barscore', :collection => @bar.weekly_scores_for(@me)
              .pane#friendsscore-always
                %table
                  %tr
                    %td.header= t 'bar.scores.friends'
                    %td.subnav#subtabs4
                      %a{:href => 'javascript:void(0)'}= t 'bar.scores.all'
                      = "-"
                      %a{:href => 'javascript:void(0)'}= t 'bar.scores.me'
                .subpanes#subpanes4
                  .subpane
                    %table.barscore-grid
                      = render :partial => 'barscore', :collection => @bar.total_scores
                  .subpane
                    %table.barscore-grid
                      = render :partial => 'barscore', :collection => @bar.total_scores_for(@me)
            %ul.tabs
              %li
                %a{:href => 'javascript:void(0)'}= t 'bar.scores.weekly'
              %li.last
                %a{:href => 'javascript:void(0)'}= t 'bar.scores.always'
          %td.bar-stats
            .header
              = t 'bar.stats.bar_stats'
            .stat
              .section
                = t 'bar.stats.bar_rank'
              .value
                = "##{@bar.rank}"
            .stat
              .section
                = t 'bar.stats.bar_weekly_activity'
              .value
                = t 'bar.stats.bar_active_members', :count => @bar.active_members
                %br
                = t 'bar.stats.bar_new_active_members', :count => @bar.new_active_members
            .stat
              .section
                = t 'bar.stats.weekly_beers'
              .value
                = image_tag 'mini-biere.png', :alt => t('beers')
                = number_with_delimiter(@bar.weekly_beers)
            .stat
              .section
                = t 'bar.stats.total_beers'
              .value
                = image_tag 'mini-biere.png', :alt => t('beers')
                = number_with_delimiter(@bar.total_beers)
            %br
            .header
              = t 'bar.stats.my_stats'
            .portrait
              = image_tag @me.profile_picture, :alt => @me.full_name, :class => 'portrait'
            .stat
              .section
                = t 'bar.stats.weekly_beers'
              .value
                = image_tag 'mini-biere.png', :alt => t('beers')
                = number_with_delimiter(@barship.weekly_beers)
            .stat
              .section
                = t 'bar.stats.total_beers'
              .value
                = image_tag 'mini-biere.png', :alt => t('beers')
                = number_with_delimiter(@barship.total_beers)
            .clear
            .stat
              .section
                = t 'bar.stats.member_since'
              .value
                = l(@barship.created_at, :format => :short)
            -#.stat
            -#  .section
            -#    = t 'bar.stats.best_rank_title'
            -#  .value
            -#    = t 'bar.stats.best_rank_value', :rank => @barship.best_rank, :date => l(@barship.best_rank_date, :format => :short)
            .stat
              .section
                = t 'bar.stats.play_count'
              .value
                = number_with_delimiter(@barship.play_count)
    %td.small.shadow
  %tr.small
    %td.small
    %td.shadow
    %td.small.shadow

#message-dialog{:title => t('bar.endgame.message.title')}
  %textarea#message-content{:rows => 3, :cols => 50}

:javascript
  $(function() {
    $('#game').flash({
      swf: "/swf/BeerQuest-#{Game::Constants::VERSION}.swf",
      width: 520,
      height: 320,
      flashvars: {
        mode: "#{@mode}",
        lang: "#{I18n.locale}",
        token: "#{@replay.token}",
        requiredVersion: #{Game::Constants::VERSION}
      }
    });
    $('#message-dialog').dialog({
      autoOpen: false,
      modal: true,
      resizable: false,
      position: [125, 320],
      buttons: {
        "#{t('bar.endgame.message.button')}": function() {
          $.post("#{endgame_message_url}", {
            token: "#{@replay.token}",
            message: $('#message-content').val()
          }, function() {
            $.get("#{async_bar_messages_url(@bar)}");
          });
          $(this).dialog('close');
        }
      },
      close: function() {
        $.get("#{async_bar_messages_url(@bar)}");
      }
    });
  });

  function endOfGame(mode, score, scoreGoal, personalHigh, barHigh)
  {
    setTimeout(function() {
      $('#message-dialog').dialog('open');
    }, 3000);
  }

  function soloBoast(score)
  {
    var url = "#{BeerQuest::FB_APP_URL}#{home_path}";
    var attachment = {
                       name: "#{t('bar.endgame.boast.post_title')}",
                       href: url,
                       //caption: "",
                       description: "#{t('bar.endgame.boast.post_message_pre')}" + score + "#{t('bar.endgame.boast.post_message_post')}",
                       media: [
                         {
                           type: 'image',
                           src: "#{static_asset_url('bq-90x90.png')}",
                           href: url
                         }
                       ]
                     };
    var links = [
                  {
                    text: "#{t('bar.endgame.boast.action')}",
                    href: url
                  }
                ];
    FB.ui(
    {
       method: "stream.publish",
       user_message_prompt: "#{t('bar.endgame.boast.prompt')}",
       //message: "",
       attachment: attachment,
       action_links: links 
    }, function(response)
    {
      if (response && response.post_id)
      {
        //alert('Post was published.');
      }
      else
      {
        //alert('Post was not published.');
      }
    });
  }

  function soloPlayAgain()
  {
    location.reload();
  }

www/app/views/bar/show.haml
- @css = 'bar'
%table.cols
  %tr.small
    %td.small
    %td
    %td.small
  %tr
    %td.small
    %td.unique-col
      %table.bar-area
        %tr
          = render :partial => 'header'
        %tr
          %td.play-field{:colspan => 2}
            #game
          %td.sidebar#scores{:rowspan => 3}
            = render :partial => 'scores'
        %tr.bottom1
          %td#rss
            = render :partial => 'rss'
          %td#activity{:rowspan => 2}
            = render :partial => 'messages'
        %tr.bottom2
          %td#stats
            = render :partial => 'stats'
    %td.small.shadow
  %tr.small
    %td.small
    %td.shadow
    %td.small.shadow

-##message-dialog{:title => t('bar.endgame.message.title')}
-#  %textarea#message-content.invalid{:rows => 3, :cols => 50}

:javascript
  $(function() {
    $('#game').flash({
      swf: "#{client_swf}",
      width: 520,
      height: 320,
      flashvars: {
        mode: "#{@mode}",
        lang: "#{I18n.locale}",
        token: "#{@replay.token}",
        requiredVersion: #{required_version}
      }
    });
    /*$('#message-dialog').dialog({
      autoOpen: false,
      modal: true,
      resizable: false,
      position: [125, 320],
      buttons: {
        "#{t('bar.endgame.message.button')}": function() {
          $.post("#{endgame_message_url}", {
            token: "#{@replay.token}",
            message: $('#message-content').val()
          }, function() {
            $.get("#{async_bar_messages_url(@bar)}");
          });
          $(this).dialog('close');
        }
      },
      close: function() {
        $.get("#{async_bar_messages_url(@bar)}");
      }
    });
    $('#message-content').bind('keyup change', function()
    {
      var len = $(this).val().length;
      if (len >= 5 && len <= 160)
      {
        $(this).removeClass('invalid');
      }
      else
      {
        $(this).addClass('invalid');
      }
    });*/
    $('.start-tutorial').click(startTutorial);
  });

  function startTutorial()
  {
    $.facebox({ ajax: "#{tutorial_url(1)}" });
  }

  function gameStarted()
  {
    if (#{@me.best_score_always} < 60)
    {
      setTimeout(startTutorial, 4000);
    }
  }

  function endOfGame(mode, score, scoreGoal, personalHigh, barHigh)
  {
    /*setTimeout(function() {
      $('#message-dialog').dialog('open');
    }, 3000);*/
  }

  function soloBoast(score)
  {
    var url = "#{BeerQuest::FB_APP_URL}#{home_path}";
    var attachment = {
                       name: "#{t('bar.endgame.boast.post_title')}",
                       href: url,
                       //caption: "",
                       description: "#{t('bar.endgame.boast.post_message_pre')}" + score + "#{t('bar.endgame.boast.post_message_post')}",
                       media: [
                         {
                           type: 'image',
                           src: "#{static_asset_url('bq-90x90.png')}",
                           href: url
                         }
                       ]
                     };
    var links = [
                  {
                    text: "#{t('bar.endgame.boast.action')}",
                    href: url
                  }
                ];
    FB.ui(
    {
       method: "stream.publish",
       user_message_prompt: "#{t('bar.endgame.boast.prompt')}",
       //message: "",
       attachment: attachment,
       action_links: links 
    }, function(response)
    {
      $.post("#{postwall_url}", {
        token: "#{@replay.token}",
        from_location: "soloBoast",
        post_id: (response && response.post_id) ? response.post_id : null
      });
    });
  }

  function soloPlayAgain()
  {
    location.reload();
  }

www/app/views/bar/widget.haml
#widget{:style => "width:#{@width}px"}
  .title= t('widget.title_html')
  #box
    .banner
      %a{:href => "#{BeerQuest::FB_APP_URL}#{bar_path(@bar)}"}
        = image_tag @bar.banner_small, :alt => @bar.name, :class => 'bar-banner'
    .content{:style => "background-color:##{@bgcolor}"}
      = number_with_delimiter(@bar.total_beers)
      = image_tag 'mini-biere.png', :alt => t('beers')
      = t('widget.beer_count')
      %hr
      .scores
        %ul
          %li Début
          %li Début
          %li Début
          %li Début
          %li Début
          %li Début
          %li Début
          %li Début
          %li Début
          %li Début
          %li Début
          - 25.times do |i|
            %li= "Joueur #{i}"
          %li Mid
          - 25.times do |i|
            %li= "Joueur #{i+25}"
          %li Fin
          %li Fin
          %li Fin
          %li Fin
          %li Fin
          %li Fin
          %li Fin
          %li Fin
          %li Fin
          %li Fin
          %li Fin
          %li Fin
      %hr
      .button
        %a{:href => "#{BeerQuest::FB_APP_URL}#{bar_path(@bar)}"}
          = image_tag "play-in-this-bar_#{I18n.locale}.png", :alt => t('home.bar.enter_button')
    .footer
      = image_tag "bq-16x16.png", :alt => t('beerquest'), :width => 16, :height => 16
      = t('widget.footer')

:javascript
  $(function()
  {
    $('.scores').autoscroll({
      step: 200,
      onEdge: function(edge) {
        if (edge.y == 'bottom') {
          $(this).autoscroll('rewind', { step: 1000000, speed: 1 });          
        }
      }
    });
  });